#!/usr/bin/env python3
"""Normalize the authored Forest Walk music into the device playback format.

Selects the authored source asset (assets/audio/forest_walk.wav OR .mp3,
never both at once without an explicit choice) and converts it with ffmpeg
into the single deterministic device playback format:

    signed 16-bit little-endian PCM, mono, 16000 Hz, raw (.pcm)

The output is a build artifact: device/esp32c3 embeds it into flash via the
music_stream component. It is generated by this tool and never committed;
only the authored WAV/MP3 belongs in version control. The browser preview
plays the authored file directly, so this tool exists for the device only.
"""

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

TARGET_RATE = 16000
TARGET_CHANNELS = 1
TARGET_CODEC = "pcm_s16le"
TARGET_FORMAT = "s16le"
BYTES_PER_SECOND = TARGET_RATE * 2  # 16-bit mono
# The PCM must fit the enlarged factory app partition next to the firmware;
# half of the 8 MB flash is a hard ceiling for a single music asset.
DEFAULT_MAX_BYTES = 4 * 1024 * 1024
SOURCE_KINDS = ("wav", "mp3")


def fail(message: str):
    print(f"compile_audio: {message}", file=sys.stderr)
    raise SystemExit(1)


def select_source(assets_dir: Path, stem: str, forced: str) -> Path:
    candidates = {kind: assets_dir / f"{stem}.{kind}" for kind in SOURCE_KINDS}
    if forced is not None:
        if forced not in SOURCE_KINDS:
            fail(f"--source must be one of {SOURCE_KINDS}, got: {forced}")
        source = candidates[forced]
        if not source.is_file():
            fail(f"selected source {source} does not exist")
        return source
    present = [kind for kind in SOURCE_KINDS if candidates[kind].is_file()]
    if not present:
        fail(
            f"no authored music found in {assets_dir}; add exactly one of "
            + " or ".join(f"{stem}.{kind}" for kind in SOURCE_KINDS)
        )
    if len(present) > 1:
        listed = ", ".join(f"{stem}.{kind}" for kind in present)
        fail(
            f"ambiguous authored music: {listed} all exist; keep exactly one "
            f"or pass --source explicitly"
        )
    return candidates[present[0]]


def probe_duration_seconds(path: Path, extra_args=()) -> float:
    result = subprocess.run(
        [
            "ffprobe", "-v", "error", *extra_args, "-show_entries",
            "format=duration", "-of", "json", str(path),
        ],
        check=True,
        capture_output=True,
        text=True,
    )
    duration = json.loads(result.stdout)["format"]["duration"]
    return float(duration)


def convert(source: Path, output: Path) -> int:
    output.parent.mkdir(parents=True, exist_ok=True)
    handle, temporary_name = tempfile.mkstemp(
        dir=output.parent, prefix=output.name, suffix=".tmp"
    )
    os.close(handle)
    temporary = Path(temporary_name)
    try:
        subprocess.run(
            [
                "ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
                "-i", str(source),
                "-map", "0:a:0", "-vn",
                "-ar", str(TARGET_RATE),
                "-ac", str(TARGET_CHANNELS),
                "-c:a", TARGET_CODEC,
                "-f", TARGET_FORMAT,
                str(temporary),
            ],
            check=True,
        )
        size = temporary.stat().st_size
        os.replace(temporary, output)
    finally:
        if temporary.exists():
            temporary.unlink()
    return size


def display_path(path: Path, repo_root: Path) -> str:
    try:
        return str(path.relative_to(repo_root))
    except ValueError:
        return str(path)


def main() -> None:
    repo_root = Path(__file__).resolve().parent.parent
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--stem", default="forest_walk")
    parser.add_argument(
        "--assets-dir", default=str(repo_root / "assets" / "audio")
    )
    parser.add_argument(
        "--output",
        default=str(repo_root / "device" / "esp32c3" / "generated" / "forest_walk.pcm"),
    )
    parser.add_argument(
        "--source", choices=SOURCE_KINDS,
        help="resolve an ambiguous wav+mp3 pair explicitly",
    )
    parser.add_argument("--max-bytes", type=int, default=DEFAULT_MAX_BYTES)
    args = parser.parse_args()

    for tool in ("ffmpeg", "ffprobe"):
        if shutil.which(tool) is None:
            fail(f"{tool} is required for audio conversion but was not found")

    source = select_source(Path(args.assets_dir), args.stem, args.source)
    source_duration = probe_duration_seconds(source)
    output = Path(args.output)
    size = convert(source, output)

    # The raw stream must decode back as exactly the target format and its
    # duration must match the source; this catches truncated conversions.
    decoded_duration = probe_duration_seconds(
        output,
        ("-f", TARGET_FORMAT, "-ar", str(TARGET_RATE), "-ch_layout", "mono"),
    )
    expected = source_duration * BYTES_PER_SECOND
    if abs(size - expected) > BYTES_PER_SECOND / 10:
        fail(
            f"converted size {size} disagrees with source duration "
            f"{source_duration:.3f}s (~{int(expected)} bytes); conversion is suspect"
        )

    generated_duration = size / BYTES_PER_SECOND
    print(f"music source: {display_path(source, repo_root)}")
    print(f"source duration: {source_duration:.3f} s")
    print(f"generated PCM: {display_path(output, repo_root)}")
    print(
        f"generated format: PCM16 little-endian / mono / {TARGET_RATE} Hz "
        f"(verified decode: {decoded_duration:.3f} s)"
    )
    print(f"generated size: {size} bytes ({generated_duration:.3f} s)")

    if size > args.max_bytes:
        fail(
            f"generated PCM is {size} bytes, over the {args.max_bytes}-byte "
            f"budget; choose a shorter track or raise the flash budget "
            f"deliberately"
        )


if __name__ == "__main__":
    main()
