#!/usr/bin/env python3
"""Normalize the authored Forest Walk music into the canonical project PCM.

Selects the authored source asset (assets/audio/forest_walk.wav OR .mp3,
never both at once without an explicit choice) and converts it with ffmpeg
into the single deterministic normalized playback format:

    signed 16-bit little-endian PCM, mono, 16000 Hz, raw (.pcm)

The canonical artifact is `.passport/assets/forest_walk.pcm` (generated
project workspace, never committed). BOTH consumers embed or serve exactly
these bytes: the ESP-IDF music_stream component flashes this file directly,
and the web bundle copies it byte-for-byte into
`.passport/web/assets/forest_walk.pcm`. There is exactly one normalization
invocation per build workflow; neither target re-converts the authored
source.

The same invocation also generates the committed MoonBit audio metadata
`src/forest_walk/generated/audio_meta.mbt` (sample rate, total sample count,
duration in microseconds, integer arithmetic only) so the portable
application can wrap the playback position at the canonical duration
without parsing MP3/WAV metadata at runtime.
"""

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

TARGET_RATE = 16000
TARGET_CHANNELS = 1
TARGET_CODEC = "pcm_s16le"
TARGET_FORMAT = "s16le"
BYTES_PER_SECOND = TARGET_RATE * 2  # 16-bit mono
# The PCM is embedded inside the factory app image (partitions.csv sizes it
# at 0x380000), so the music must leave room for the firmware itself: this
# ceiling reserves at least 1 MiB of the partition for code and data.
# tools/test_compile_audio.py pins the budget against partitions.csv; the
# ESP-IDF linker remains the final authoritative capacity check.
MAX_PCM_BYTES = 0x280000
SOURCE_KINDS = ("wav", "mp3")

# Blank lines between blocks match `moon fmt` output exactly, so the
# regenerated file is always fmt-stable (CI runs moon fmt and then
# git diff --exit-code).
META_HEADER = """///|
/// Generated by tools/compile_audio.py from the authored music source; do
/// not edit by hand. Regenerate together with the canonical
/// .passport/assets/forest_walk.pcm via `moon run tools/assets.mbtx`.

///|
/// Canonical normalized PCM sample rate in hertz (PCM16 LE, mono,
/// headerless).
pub const AUDIO_SAMPLE_RATE : Int = {sample_rate}

///|
/// Total PCM sample count of the canonical artifact (byte length / 2).
pub const AUDIO_TOTAL_SAMPLES : Int = {total_samples}

///|
/// Duration of one loop of the canonical artifact in microseconds
/// (total_samples * 1_000_000 / sample_rate, integer division).
pub const AUDIO_DURATION_US : Int64 = {duration_us}L
"""


def fail(message: str):
    print(f"compile_audio: {message}", file=sys.stderr)
    raise SystemExit(1)


def select_source(assets_dir: Path, stem: str, forced: str) -> Path:
    candidates = {kind: assets_dir / f"{stem}.{kind}" for kind in SOURCE_KINDS}
    if forced is not None:
        if forced not in SOURCE_KINDS:
            fail(f"--source must be one of {SOURCE_KINDS}, got: {forced}")
        source = candidates[forced]
        if not source.is_file():
            fail(f"selected source {source} does not exist")
        return source
    present = [kind for kind in SOURCE_KINDS if candidates[kind].is_file()]
    if not present:
        fail(
            f"no authored music found in {assets_dir}; add exactly one of "
            + " or ".join(f"{stem}.{kind}" for kind in SOURCE_KINDS)
        )
    if len(present) > 1:
        listed = ", ".join(f"{stem}.{kind}" for kind in present)
        fail(
            f"ambiguous authored music: {listed} all exist; keep exactly one "
            f"or pass --source explicitly"
        )
    return candidates[present[0]]


def probe_duration_seconds(path: Path, extra_args=()) -> float:
    result = subprocess.run(
        [
            "ffprobe", "-v", "error", *extra_args, "-show_entries",
            "format=duration", "-of", "json", str(path),
        ],
        check=True,
        capture_output=True,
        text=True,
    )
    duration = json.loads(result.stdout)["format"]["duration"]
    return float(duration)


def convert(source: Path, output: Path) -> int:
    output.parent.mkdir(parents=True, exist_ok=True)
    handle, temporary_name = tempfile.mkstemp(
        dir=output.parent, prefix=output.name, suffix=".tmp"
    )
    os.close(handle)
    temporary = Path(temporary_name)
    try:
        subprocess.run(
            [
                "ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
                "-i", str(source),
                "-map", "0:a:0", "-vn",
                "-ar", str(TARGET_RATE),
                "-ac", str(TARGET_CHANNELS),
                "-c:a", TARGET_CODEC,
                "-f", TARGET_FORMAT,
                str(temporary),
            ],
            check=True,
        )
        size = temporary.stat().st_size
        os.replace(temporary, output)
    finally:
        if temporary.exists():
            temporary.unlink()
    return size


def display_path(path: Path, repo_root: Path) -> str:
    try:
        return str(path.relative_to(repo_root))
    except ValueError:
        return str(path)


def emit_meta(meta_output: Path, size: int) -> None:
    """Write the deterministic MoonBit audio metadata source.

    The values derive only from the canonical PCM byte size, so the same
    source asset always regenerates the identical file (CI verifies this
    with git diff --exit-code).
    """
    total_samples = size // 2
    # Integer arithmetic only: the application wraps the playback position
    # with modulo against this duration.
    duration_us = total_samples * 1_000_000 // TARGET_RATE
    meta_output.parent.mkdir(parents=True, exist_ok=True)
    meta_output.write_text(
        META_HEADER.format(
            sample_rate=TARGET_RATE,
            total_samples=total_samples,
            duration_us=duration_us,
        ),
        encoding="utf-8",
    )


def main() -> None:
    repo_root = Path(__file__).resolve().parent.parent
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--stem", default="forest_walk")
    parser.add_argument(
        "--assets-dir", default=str(repo_root / "assets" / "audio")
    )
    parser.add_argument(
        "--output",
        default=str(repo_root / ".passport" / "assets" / "forest_walk.pcm"),
    )
    parser.add_argument(
        "--meta-output",
        default=str(
            repo_root / "src" / "forest_walk" / "generated" / "audio_meta.mbt"
        ),
    )
    parser.add_argument(
        "--source", choices=SOURCE_KINDS,
        help="resolve an ambiguous wav+mp3 pair explicitly",
    )
    parser.add_argument("--max-bytes", type=int, default=MAX_PCM_BYTES)
    args = parser.parse_args()

    for tool in ("ffmpeg", "ffprobe"):
        if shutil.which(tool) is None:
            fail(f"{tool} is required for audio conversion but was not found")

    source = select_source(Path(args.assets_dir), args.stem, args.source)
    source_duration = probe_duration_seconds(source)
    output = Path(args.output)
    size = convert(source, output)

    # The raw stream must decode back as exactly the target format and its
    # duration must match the source; this catches truncated conversions.
    decoded_duration = probe_duration_seconds(
        output,
        ("-f", TARGET_FORMAT, "-ar", str(TARGET_RATE), "-ch_layout", "mono"),
    )
    expected = source_duration * BYTES_PER_SECOND
    if abs(size - expected) > BYTES_PER_SECOND / 10:
        fail(
            f"converted size {size} disagrees with source duration "
            f"{source_duration:.3f}s (~{int(expected)} bytes); conversion is suspect"
        )

    if size == 0 or size % 2 != 0:
        fail(f"canonical PCM must be non-empty and even-length, got {size} bytes")

    emit_meta(Path(args.meta_output), size)

    generated_duration = size / BYTES_PER_SECOND
    print(f"music source: {display_path(source, repo_root)}")
    print(f"source duration: {source_duration:.3f} s")
    print(f"canonical PCM: {display_path(output, repo_root)}")
    print(
        f"canonical format: PCM16 little-endian / mono / {TARGET_RATE} Hz "
        f"(verified decode: {decoded_duration:.3f} s)"
    )
    print(f"canonical size: {size} bytes ({generated_duration:.3f} s)")
    print(f"audio metadata: {display_path(Path(args.meta_output), repo_root)}")

    if size > args.max_bytes:
        fail(
            f"generated PCM is {size} bytes, over the {args.max_bytes}-byte "
            f"device flash budget (the PCM shares the factory app partition "
            f"with the firmware); choose a shorter track or raise the "
            f"budget deliberately"
        )


if __name__ == "__main__":
    main()
