#!/usr/bin/env python3
"""Normalize Forest Walk music to PCM16 LE mono 16 kHz."""

import argparse
import json
import math
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

TARGET_RATE = 16000
TARGET_CHANNELS = 1
TARGET_CODEC = "pcm_s16le"
TARGET_FORMAT = "s16le"
BYTES_PER_SECOND = TARGET_RATE * 2
MAX_PCM_BYTES = 0x280000
SOURCE_KINDS = ("wav", "mp3")

META_HEADER = """///|
/// Generated by tools/compile_audio.py from the authored music source; do
/// not edit by hand. Regenerate together with the canonical
/// .passport/assets/forest_walk.pcm via `moon run tools/assets.mbtx`.

///|
/// Canonical normalized PCM sample rate in hertz (PCM16 LE, mono,
/// headerless).
pub const AUDIO_SAMPLE_RATE : Int = {sample_rate}

///|
/// Total PCM sample count of the canonical artifact (byte length / 2).
pub const AUDIO_TOTAL_SAMPLES : Int = {total_samples}

///|
/// Duration of one loop of the canonical artifact in microseconds
/// (total_samples * 1_000_000 / sample_rate, integer division).
pub const AUDIO_DURATION_US : Int64 = {duration_us}L
"""


def fail(message: str):
    print(f"compile_audio: {message}", file=sys.stderr)
    raise SystemExit(1)


def select_source(assets_dir: Path, stem: str, forced: str | None) -> Path:
    candidates = {kind: assets_dir / f"{stem}.{kind}" for kind in SOURCE_KINDS}
    if forced is not None:
        source = candidates[forced]
        if not source.is_file():
            fail(f"selected source {source} does not exist")
        return source

    present = [kind for kind in SOURCE_KINDS if candidates[kind].is_file()]
    if not present:
        fail(
            f"no authored music found in {assets_dir}; add exactly one of "
            + " or ".join(f"{stem}.{kind}" for kind in SOURCE_KINDS)
        )
    if len(present) > 1:
        listed = ", ".join(f"{stem}.{kind}" for kind in present)
        fail(f"ambiguous authored music: {listed}; keep one or pass --source")
    return candidates[present[0]]


def probe_duration_seconds(path: Path, extra_args=()) -> float:
    result = subprocess.run(
        [
            "ffprobe",
            "-v",
            "error",
            *extra_args,
            "-show_entries",
            "format=duration",
            "-of",
            "json",
            str(path),
        ],
        check=True,
        capture_output=True,
        text=True,
    )
    duration = float(json.loads(result.stdout)["format"]["duration"])
    if not math.isfinite(duration) or duration <= 0:
        fail(f"invalid media duration for {path}: {duration}")
    return duration


def convert(source: Path, output: Path, max_bytes: int) -> int:
    output.parent.mkdir(parents=True, exist_ok=True)
    handle, temporary_name = tempfile.mkstemp(
        dir=output.parent, prefix=output.name, suffix=".tmp"
    )
    os.close(handle)
    temporary = Path(temporary_name)
    try:
        subprocess.run(
            [
                "ffmpeg",
                "-y",
                "-hide_banner",
                "-loglevel",
                "error",
                "-i",
                str(source),
                "-map",
                "0:a:0",
                "-vn",
                "-ar",
                str(TARGET_RATE),
                "-ac",
                str(TARGET_CHANNELS),
                "-c:a",
                TARGET_CODEC,
                "-f",
                TARGET_FORMAT,
                str(temporary),
            ],
            check=True,
        )
        size = temporary.stat().st_size
        if size == 0 or size % 2 != 0:
            fail(f"canonical PCM must be non-empty and even-length, got {size} bytes")
        if size > max_bytes:
            fail(
                f"generated PCM is {size} bytes, over the {max_bytes}-byte "
                "device flash budget"
            )
        os.replace(temporary, output)
        return size
    finally:
        if temporary.exists():
            temporary.unlink()


def display_path(path: Path, repo_root: Path) -> str:
    try:
        return str(path.relative_to(repo_root))
    except ValueError:
        return str(path)


def emit_meta(meta_output: Path, size: int) -> None:
    total_samples = size // 2
    duration_us = total_samples * 1_000_000 // TARGET_RATE
    text = META_HEADER.format(
        sample_rate=TARGET_RATE,
        total_samples=total_samples,
        duration_us=duration_us,
    )
    meta_output.parent.mkdir(parents=True, exist_ok=True)
    handle, temporary_name = tempfile.mkstemp(
        dir=meta_output.parent, prefix=meta_output.name, suffix=".tmp", text=True
    )
    os.close(handle)
    temporary = Path(temporary_name)
    try:
        temporary.write_text(text, encoding="utf-8", newline="\n")
        os.replace(temporary, meta_output)
    finally:
        if temporary.exists():
            temporary.unlink()


def main() -> None:
    repo_root = Path(__file__).resolve().parent.parent
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--stem", default="forest_walk")
    parser.add_argument("--assets-dir", default=str(repo_root / "assets" / "audio"))
    parser.add_argument(
        "--output", default=str(repo_root / ".passport" / "assets" / "forest_walk.pcm")
    )
    parser.add_argument(
        "--meta-output",
        default=str(repo_root / "src" / "forest_walk" / "generated" / "audio_meta.mbt"),
    )
    parser.add_argument("--source", choices=SOURCE_KINDS)
    parser.add_argument("--max-bytes", type=int, default=MAX_PCM_BYTES)
    args = parser.parse_args()

    if args.max_bytes <= 0:
        fail("--max-bytes must be positive")
    for tool in ("ffmpeg", "ffprobe"):
        if shutil.which(tool) is None:
            fail(f"{tool} is required for audio conversion but was not found")

    source = select_source(Path(args.assets_dir), args.stem, args.source)
    source_duration = probe_duration_seconds(source)
    output = Path(args.output)
    size = convert(source, output, args.max_bytes)

    decoded_duration = probe_duration_seconds(
        output,
        ("-f", TARGET_FORMAT, "-ar", str(TARGET_RATE), "-ch_layout", "mono"),
    )
    expected = source_duration * BYTES_PER_SECOND
    if abs(size - expected) > BYTES_PER_SECOND / 10:
        output.unlink(missing_ok=True)
        fail(
            f"converted size {size} disagrees with source duration "
            f"{source_duration:.3f}s (~{int(expected)} bytes)"
        )

    emit_meta(Path(args.meta_output), size)

    print(f"music source: {display_path(source, repo_root)}")
    print(f"source duration: {source_duration:.3f} s")
    print(f"canonical PCM: {display_path(output, repo_root)}")
    print(
        f"canonical format: PCM16 little-endian / mono / {TARGET_RATE} Hz "
        f"(verified decode: {decoded_duration:.3f} s)"
    )
    print(f"canonical size: {size} bytes ({size / BYTES_PER_SECOND:.3f} s)")
    print(f"audio metadata: {display_path(Path(args.meta_output), repo_root)}")


if __name__ == "__main__":
    main()
